In [1]:
# import libraries
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import plotly.express as px
from scipy import stats
import statsmodels.formula.api as smf
# from scipy.stats import norm, binom

In [2]:
# read data
# Fahrzeuge = pd.read_csv(r'C:\Users\Admin\Desktop\Fahrzeuganalyse\data\all_vehicles_model.csv', delimiter=';')
# delimiter=';' muss beim Einlesen der csv dabei sein, sonst wieder Fehlermeldung

In [3]:
# clean data
# clean = Fahrzeuge.dropna(axis=1, inplace=True)
# NaN, Spalten löschen

In [4]:
# cleaned data to a new dataframe
# analyze_df = pd.DataFrame(Fahrzeuge)

In [5]:
# write cleaned to a new csv file
# analyze_df.to_csv(r'C:\Users\Admin\Desktop\Fahrzeuganalyse\data\cleaned_data_vehicles.csv',
                  # sep=';',
                  # header=True,
                  # mode='w',
                  # encoding='utf-8',
                  # index=False)

In [6]:
# read csv file, create dataframe
vehicles = pd.read_csv(r'C:\Users\Admin\Desktop\Fahrzeuganalyse\data\cleaned_data_vehicles.csv', delimiter=';')

In [7]:
# check dataframe df.info()
vehicles.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 47523 entries, 0 to 47522
Data columns (total 63 columns):
 #   Column                                       Non-Null Count  Dtype
---  ------                                       --------------  -----
 0   Make                                         47523 non-null  object
 1   Model                                        47523 non-null  object
 2   Annual Petroleum Consumption For Fuel Type1  47523 non-null  float64
 3   Annual Petroleum Consumption For Fuel Type2  47523 non-null  float64
 4   Time to charge at 120V                       47523 non-null  float64
 5   Time to charge at 240V                       47523 non-null  float64
 6   City Mpg For Fuel Type1                      47523 non-null  int64
 7   Unrounded City Mpg For Fuel Type1 (2)        47523 non-null  float64
 8   City Mpg For Fuel Type2                      47523 non-null  int64
 9   Unrounded City Mpg For Fuel Type2            47523 non-null  float64
 10  City gasoline consumption                    47523 non-null  float64
 11  City electricity consumption                 47523 non-null  float64
 12  EPA city utility factor                      47523 non-null  float64
 13  Co2 Fuel Type1                               47523 non-null  int64
 14  Co2 Fuel Type2                               47523 non-null  int64
 15  Co2  Tailpipe For Fuel Type2                 47523 non-null  float64
 16  Co2  Tailpipe For Fuel Type1                 47523 non-null  float64
 17  Combined Mpg For Fuel Type1                  47523 non-null  int64
 18  Unrounded Combined Mpg For Fuel Type1        47523 non-null  float64
 19  Combined Mpg For Fuel Type2                  47523 non-null  int64
 20  Unrounded Combined Mpg For Fuel Type2        47523 non-null  float64
 21  Combined electricity consumption             47523 non-null  float64
 22  Combined gasoline consumption                47523 non-null  float64
 23  EPA combined utility factor                  47523 non-null  float64
 24  EPA model type index                         47523 non-null  int64
 25  Annual Fuel Cost For Fuel Type1              47523 non-null  int64
 26  Annual Fuel Cost For Fuel Type2              47523 non-null  int64
 27  Fuel Type                                    47523 non-null  object
 28  Fuel Type1                                   47523 non-null  object
 29  Highway Mpg For Fuel Type1                   47523 non-null  int64
 30  Unrounded Highway Mpg For Fuel Type1         47523 non-null  float64
 31  Highway Mpg For Fuel Type2                   47523 non-null  int64
 32  Unrounded Highway Mpg For Fuel Type2         47523 non-null  float64
 33  Highway gasoline consumption                 47523 non-null  float64
 34  Highway electricity consumption              47523 non-null  float64
 35  EPA highway utility factor                   47523 non-null  float64
 36  Hatchback luggage volume                     47523 non-null  int64
 37  Hatchback passenger volume                   47523 non-null  int64
 38  ID                                           47523 non-null  int64
 39  2 door luggage volume                        47523 non-null  int64
 40  4 door luggage volume                        47523 non-null  int64
 41  PHEV Blended                                 47523 non-null  bool
 42  2-door passenger volume                      47523 non-null  int64
 43  4-door passenger volume                      47523 non-null  int64
 44  Range For Fuel Type1                         47523 non-null  int64
 45  Range  City For Fuel Type1                   47523 non-null  float64
 46  Range  City For Fuel Type2                   47523 non-null  float64
 47  Range  Highway For Fuel Type1                47523 non-null  float64
 48  Range  Highway For Fuel Type2                47523 non-null  float64
 49  Unadjusted City Mpg For Fuel Type1           47523 non-null  float64
 50  Unadjusted City Mpg For Fuel Type2           47523 non-null  float64
 51  Unadjusted Highway Mpg For Fuel Type1        47523 non-null  float64
 52  Unadjusted Highway Mpg For Fuel Type2        47523 non-null  float64
 53  Vehicle Size Class                           47523 non-null  object
 54  Year                                         47523 non-null  int64
 55  You Save/Spend                               47523 non-null  int64
 56  charge240b                                   47523 non-null  float64
 57  Created On                                   47523 non-null  object
 58  Modified On                                  47523 non-null  object
 59  PHEV City                                    47523 non-null  int64
 60  PHEV Highway                                 47523 non-null  int64
 61  PHEV Combined                                47523 non-null  int64
 62  baseModel                                    47523 non-null  object
dtypes: bool(1), float64(30), int64(24), object(8)
memory usage: 22.5+ MB

In [8]:
""" column type bool (1)
41  PHEV Blended  47523 non-null  bool
"""

' column type bool (1)\n41  PHEV Blended  47523 non-null  bool\n'

In [9]:
""" column type float64 (30)
 2   Annual Petroleum Consumption For Fuel Type1  47523 non-null  float64
 3   Annual Petroleum Consumption For Fuel Type2  47523 non-null  float64
 4   Time to charge at 120V                       47523 non-null  float64
 5   Time to charge at 240V                       47523 non-null  float64
 7   Unrounded City Mpg For Fuel Type1 (2)        47523 non-null  float64
 9   Unrounded City Mpg For Fuel Type2            47523 non-null  float64
 10  City gasoline consumption                    47523 non-null  float64
 11  City electricity consumption                 47523 non-null  float64
 12  EPA city utility factor                      47523 non-null  float64
 15  Co2  Tailpipe For Fuel Type2                 47523 non-null  float64
 16  Co2  Tailpipe For Fuel Type1                 47523 non-null  float64
 18  Unrounded Combined Mpg For Fuel Type1        47523 non-null  float64
 20  Unrounded Combined Mpg For Fuel Type2        47523 non-null  float64
 21  Combined electricity consumption             47523 non-null  float64
 22  Combined gasoline consumption                47523 non-null  float64
 23  EPA combined utility factor                  47523 non-null  float64
 30  Unrounded Highway Mpg For Fuel Type1         47523 non-null  float64
 32  Unrounded Highway Mpg For Fuel Type2         47523 non-null  float64
 33  Highway gasoline consumption                 47523 non-null  float64
 34  Highway electricity consumption              47523 non-null  float64
 35  EPA highway utility factor                   47523 non-null  float64
 45  Range  City For Fuel Type1                   47523 non-null  float64
 46  Range  City For Fuel Type2                   47523 non-null  float64
 47  Range  Highway For Fuel Type1                47523 non-null  float64
 48  Range  Highway For Fuel Type2                47523 non-null  float64
 49  Unadjusted City Mpg For Fuel Type1           47523 non-null  float64
 50  Unadjusted City Mpg For Fuel Type2           47523 non-null  float64
 51  Unadjusted Highway Mpg For Fuel Type1        47523 non-null  float64
 52  Unadjusted Highway Mpg For Fuel Type2        47523 non-null  float64
 56  charge240b                                   47523 non-null  float64"""

' column type float64 (30)\n 2   Annual Petroleum Consumption For Fuel Type1  47523 non-null  float64\n 3   Annual Petroleum Consumption For Fuel Type2  47523 non-null  float64\n 4   Time to charge at 120V                       47523 non-null  float64\n 5   Time to charge at 240V                       47523 non-null  float64\n 7   Unrounded City Mpg For Fuel Type1 (2)        47523 non-null  float64\n 9   Unrounded City Mpg For Fuel Type2            47523 non-null  float64\n 10  City gasoline consumption                    47523 non-null  float64\n 11  City electricity consumption                 47523 non-null  float64\n 12  EPA city utility factor                      47523 non-null  float64\n 15  Co2  Tailpipe For Fuel Type2                 47523 non-null  float64\n 16  Co2  Tailpipe For Fuel Type1                 47523 non-null  float64\n 18  Unrounded Combined Mpg For Fuel Type1        47523 non-null  float64\n 20  Unrounded Combined Mpg For Fuel Type2        47523 non-null  float64\n 21  Combined electricity consumption             47523 non-null  float64\n 22  Combined gasoline consumption                47523 non-null  float64\n 23  EPA combined utility factor                  47523 non-null  float64\n 30  Unrounded Highway Mpg For Fuel Type1         47523 non-null  float64\n 32  Unrounded Highway Mpg For Fuel Type2         47523 non-null  float64\n 33  Highway gasoline consumption                 47523 non-null  float64\n 34  Highway electricity consumption              47523 non-null  float64\n 35  EPA highway utility factor                   47523 non-null  float64\n 45  Range  City For Fuel Type1                   47523 non-null  float64\n 46  Range  City For Fuel Type2                   47523 non-null  float64\n 47  Range  Highway For Fuel Type1                47523 non-null  float64\n 48  Range  Highway For Fuel Type2                47523 non-null  float64\n 49  Unadjusted City Mpg For Fuel Type1           47523 non-null  float64\n 50  Unadjusted City Mpg For Fuel Type2           47523 non-null  float64\n 51  Unadjusted Highway Mpg For Fuel Type1        47523 non-null  float64\n 52  Unadjusted Highway Mpg For Fuel Type2        47523 non-null  float64\n 56  charge240b                                   47523 non-null  float64'

In [10]:
""" column type int64 (24)
 6   City Mpg For Fuel Type1                      47523 non-null  int64
 8   City Mpg For Fuel Type2                      47523 non-null  int64
 13  Co2 Fuel Type1                               47523 non-null  int64
 14  Co2 Fuel Type2                               47523 non-null  int64
 17  Combined Mpg For Fuel Type1                  47523 non-null  int64
 19  Combined Mpg For Fuel Type2                  47523 non-null  int64
 24  EPA model type index                         47523 non-null  int64
 25  Annual Fuel Cost For Fuel Type1              47523 non-null  int64
 26  Annual Fuel Cost For Fuel Type2              47523 non-null  int64
 29  Highway Mpg For Fuel Type1                   47523 non-null  int64
 31  Highway Mpg For Fuel Type2                   47523 non-null  int64
 36  Hatchback luggage volume                     47523 non-null  int64
 37  Hatchback passenger volume                   47523 non-null  int64
 38  ID                                           47523 non-null  int64
 39  2 door luggage volume                        47523 non-null  int64
 40  4 door luggage volume                        47523 non-null  int64
 42  2-door passenger volume                      47523 non-null  int64
 43  4-door passenger volume                      47523 non-null  int64
 44  Range For Fuel Type1                         47523 non-null  int64
 54  Year                                         47523 non-null  int64
 55  You Save/Spend                               47523 non-null  int64
 59  PHEV City                                    47523 non-null  int64
 60  PHEV Highway                                 47523 non-null  int64
 61  PHEV Combined                                47523 non-null  int64"""

' column type int64 (24)\n 6   City Mpg For Fuel Type1                      47523 non-null  int64\n 8   City Mpg For Fuel Type2                      47523 non-null  int64\n 13  Co2 Fuel Type1                               47523 non-null  int64\n 14  Co2 Fuel Type2                               47523 non-null  int64\n 17  Combined Mpg For Fuel Type1                  47523 non-null  int64\n 19  Combined Mpg For Fuel Type2                  47523 non-null  int64\n 24  EPA model type index                         47523 non-null  int64\n 25  Annual Fuel Cost For Fuel Type1              47523 non-null  int64\n 26  Annual Fuel Cost For Fuel Type2              47523 non-null  int64\n 29  Highway Mpg For Fuel Type1                   47523 non-null  int64\n 31  Highway Mpg For Fuel Type2                   47523 non-null  int64\n 36  Hatchback luggage volume                     47523 non-null  int64\n 37  Hatchback passenger volume                   47523 non-null  int64\n 38  ID                                           47523 non-null  int64\n 39  2 door luggage volume                        47523 non-null  int64\n 40  4 door luggage volume                        47523 non-null  int64\n 42  2-door passenger volume                      47523 non-null  int64\n 43  4-door passenger volume                      47523 non-null  int64\n 44  Range For Fuel Type1                         47523 non-null  int64\n 54  Year                                         47523 non-null  int64\n 55  You Save/Spend                               47523 non-null  int64\n 59  PHEV City                                    47523 non-null  int64\n 60  PHEV Highway                                 47523 non-null  int64\n 61  PHEV Combined                                47523 non-null  int64'

In [11]:
""" column type object (8)
 0   Make                                         47523 non-null  object
 1   Model                                        47523 non-null  object
 27  Fuel Type                                    47523 non-null  object
 28  Fuel Type1                                   47523 non-null  object
 53  Vehicle Size Class                           47523 non-null  object
 57  Created On                                   47523 non-null  object
 58  Modified On                                  47523 non-null  object
 62  baseModel                                    47523 non-null  object"""

' column type object (8)\n 0   Make                                         47523 non-null  object\n 1   Model                                        47523 non-null  object\n 27  Fuel Type                                    47523 non-null  object\n 28  Fuel Type1                                   47523 non-null  object\n 53  Vehicle Size Class                           47523 non-null  object\n 57  Created On                                   47523 non-null  object\n 58  Modified On                                  47523 non-null  object\n 62  baseModel                                    47523 non-null  object'

In [12]:
# show first 5 rows df.head()
vehicles.head()

,Make,Model,Annual Petroleum Consumption For Fuel Type1,Annual Petroleum Consumption For Fuel Type2,Time to charge at 120V,Time to charge at 240V,City Mpg For Fuel Type1,Unrounded City Mpg For Fuel Type1 (2),City Mpg For Fuel Type2,Unrounded City Mpg For Fuel Type2,...,Vehicle Size Class,Year,You Save/Spend,charge240b,Created On,Modified On,PHEV City,PHEV Highway,PHEV Combined,baseModel
0,Ford,Bronco 4WD,22.885385,0.0,0.0,0.0,12,0.0,0,0.0,...,Special Purpose Vehicles,1986,-11250,0.0,2013-01-01,2013-01-01,0,0,0,Bronco
1,Ford,LTD Wagon,15.658421,0.0,0.0,0.0,17,0.0,0,0.0,...,Midsize Station Wagons,1984,-4750,0.0,2013-01-01,2013-01-01,0,0,0,LTD
2,Chevrolet,S10 Pickup 2WD,12.935217,0.0,0.0,0.0,21,0.0,0,0.0,...,Small Pickup Trucks 2WD,1984,-2250,0.0,2013-01-01,2013-01-01,0,0,0,S10 Pickup
3,Dodge,Ram 50 Pickup 2WD,14.875500,0.0,0.0,0.0,18,0.0,0,0.0,...,Small Pickup Trucks 2WD,1984,-4000,0.0,2013-01-01,2013-01-01,0,0,0,Ram 50 Pickup
4,Ford,Ranger Pickup 2WD,15.658421,0.0,0.0,0.0,18,0.0,0,0.0,...,Small Pickup Trucks 2WD,1984,-4750,0.0,2013-01-01,2013-01-01,0,0,0,Ranger

In [13]:
vehicles.describe()

,Annual Petroleum Consumption For Fuel Type1,Annual Petroleum Consumption For Fuel Type2,Time to charge at 120V,Time to charge at 240V,City Mpg For Fuel Type1,Unrounded City Mpg For Fuel Type1 (2),City Mpg For Fuel Type2,Unrounded City Mpg For Fuel Type2,City gasoline consumption,City electricity consumption,...,Unadjusted City Mpg For Fuel Type1,Unadjusted City Mpg For Fuel Type2,Unadjusted Highway Mpg For Fuel Type1,Unadjusted Highway Mpg For Fuel Type2,Year,You Save/Spend,charge240b,PHEV City,PHEV Highway,PHEV Combined
count,47523.000000,47523.000000,47523.0,47523.000000,47523.000000,47523.000000,47523.000000,47523.000000,47523.000000,47523.000000,...,47523.000000,47523.000000,47523.000000,47523.000000,47523.000000,47523.000000,47523.000000,47523.000000,47523.000000,47523.000000
mean,15.173212,0.190030,0.0,0.178136,19.662079,8.940989,0.896303,0.770897,0.000501,0.981353,...,25.073608,1.196986,35.997452,0.987824,2004.302401,-5385.355512,0.015435,0.311302,0.313553,0.310923
std,4.488236,0.976448,0.0,1.313176,11.914322,15.857898,6.821359,6.755519,0.036616,6.637931,...,17.067712,9.648902,15.083867,6.637179,12.534077,4445.321813,0.321030,4.035418,3.894750,3.946077
min,0.047081,0.000000,0.0,0.000000,6.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,1984.000000,-38500.000000,0.000000,0.000000,0.000000,0.000000
25%,12.396250,0.000000,0.0,0.000000,15.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,18.700000,0.000000,28.200000,0.000000,1993.000000,-8250.000000,0.000000,0.000000,0.000000,0.000000
50%,14.875500,0.000000,0.0,0.000000,18.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,22.000000,0.000000,33.900000,0.000000,2005.000000,-5250.000000,0.000000,0.000000,0.000000,0.000000
75%,17.500588,0.000000,0.0,0.000000,21.000000,17.598600,0.000000,0.000000,0.000000,0.000000,...,26.666700,0.000000,40.000000,0.000000,2015.000000,-2500.000000,0.000000,0.000000,0.000000,0.000000
max,42.501429,16.528333,0.0,19.000000,153.000000,155.824200,145.000000,145.083500,5.350000,122.000000,...,224.800000,207.262200,187.100000,173.143600,2025.000000,9500.000000,9.600000,97.000000,81.000000,89.000000

In [14]:
vehicles.Make.nunique()

144

In [15]:
vehicles.Make.value_counts()

Make
Chevrolet                             4420
Ford                                  3821
GMC                                   2777
Dodge                                 2690
BMW                                   2469
                                      ...
General Motors                           1
Azure Dynamics                           1
S and S Coach Company  E.p. Dutton       1
E. P. Dutton, Inc.                       1
Panos                                    1
Name: count, Length: 144, dtype: int64

### 10 Fragen zur Fahrzeuganalyse

### 1. Welche Automarken verbrauchen am meisten Erdöl pro Jahr?

In [16]:
# Gruppieren nach Marke und Mittelwert berechnen
verbrauch_pro_marke = (
    vehicles.groupby("Make")["Annual Petroleum Consumption For Fuel Type1"]
    .mean()
    .reset_index()
    .rename(columns={"Annual Petroleum Consumption For Fuel Type1": "AvgPetroleumConsumption"})
    .sort_values("AvgPetroleumConsumption", ascending=False)
)

fig = px.bar(
    verbrauch_pro_marke,
    x="Make",
    y="AvgPetroleumConsumption",
    title="Durchschnittlicher jährlicher Erdölverbrauch pro Automarke",
    labels={"Make": "Automarke", "AvgPetroleumConsumption": "Verbrauch (Gallonen/Jahr)"},
    color="AvgPetroleumConsumption",
    color_continuous_scale="Reds"
)

fig.update_layout(
    xaxis_tickangle=-45,
    template="plotly_white"
)

fig.show()

### 2. Welche Fahrzeugmodelle haben den höchsten und niedrigsten Stadtverbrauch (City MPG)?

In [17]:
# Wichtige Spalten prüfen & filtern
vehicles_filtered = vehicles[["Make", "Model", "City Mpg For Fuel Type1"]].dropna()

# Duplikate vermeiden durch Kombination von Name + Modell + Verbrauch
vehicles_filtered["Fahrzeug"] = (
    vehicles_filtered["Make"] + " " + vehicles_filtered["Model"] +
    " (" + vehicles_filtered["City Mpg For Fuel Type1"].astype(str) + " MPG)"
)

# Nur eindeutige City MPG-Werte zulassen
vehicles_unique = vehicles_filtered.drop_duplicates(subset=["City Mpg For Fuel Type1"])

# Top 10 effizienteste Fahrzeuge
top10 = vehicles_unique.sort_values("City Mpg For Fuel Type1", ascending=False).head(10)
top10["Effizienzgruppe"] = "Top 10 (effizient)"

# Flop 10 ineffizienteste Fahrzeuge
flop10 = vehicles_unique[vehicles_unique["City Mpg For Fuel Type1"] > 0].sort_values("City Mpg For Fuel Type1").head(10)
flop10["Effizienzgruppe"] = "Flop 10 (ineffizient)"

# Kombinieren
combined = pd.concat([top10, flop10])

# Balkendiagramm erstellen
fig = px.bar(
    combined,
    x="City Mpg For Fuel Type1",
    y="Fahrzeug",
    color="Effizienzgruppe",
    orientation="h",
    title="Top & Flop 10 Fahrzeugmodelle nach City MPG (Stadtverbrauch)",
    labels={"City Mpg For Fuel Type1": "Miles per Gallon (City)", "Fahrzeug": "Fahrzeugmodell"},
    color_discrete_map={
        "Top 10 (effizient)": "green",
        "Flop 10 (ineffizient)": "red"
    }
)

fig.update_layout(
    yaxis=dict(categoryorder="total ascending"),
    template="plotly_white",
    height=700
)

fig.show()

### 3. Wie unterscheidet sich der durchschnittliche Erdölverbrauch je nach Kraftstofftyp (Fuel Type1)?

In [18]:
# Nur relevante Spalten & Nullwerte entfernen
fuel_df = vehicles[["Fuel Type1", "Annual Petroleum Consumption For Fuel Type1"]].dropna()

# Gruppieren nach Kraftstofftyp & Ø-Verbrauch berechnen
avg_consumption = (
    fuel_df
    .groupby("Fuel Type1")["Annual Petroleum Consumption For Fuel Type1"]
    .mean()
    .reset_index()
    .rename(columns={"Annual Petroleum Consumption For Fuel Type1": "Ø Verbrauch (Gallonen/Jahr)"})
)

# Sortieren nach Verbrauch
avg_consumption = avg_consumption.sort_values("Ø Verbrauch (Gallonen/Jahr)", ascending=False)

# Plot erstellen
fig = px.bar(
    avg_consumption,
    x="Fuel Type1",
    y="Ø Verbrauch (Gallonen/Jahr)",
    title="Ø jährlicher Erdölverbrauch nach Kraftstofftyp (Fuel Type1)",
    color="Fuel Type1",
    template="plotly_white"
)

fig.update_layout(showlegend=False)
fig.show()

### 4. Entwicklung des durchschnittlichen Erdölverbrauchs nach Modelljahr, 1984 bis 2025
Interpretation
1995 Kurve "sackt" ab - was ist passiert?
nach 1996 sinkender Erdölverbrauch
2023 Kurve "sackt" ab
2024 Kurve steigt etwas mehr als diese 2023 sank
Welche Fahrzeugmodelle haben die höchsten Verbrauchswerte bei gleichzeitig geringem City MPG?

In [19]:
vehicles["Fuel Type1"].value_counts()

Fuel Type1
Regular Gasoline     30426
Premium Gasoline     14801
Diesel                1274
Electricity            766
Midgrade Gasoline      164
Natural Gas             60
Hydrogen                32
Name: count, dtype: int64

In [20]:
# Relevante Spalten & NaNs entfernen
yearly_consumption = vehicles[[
    "Year", "Annual Petroleum Consumption For Fuel Type1"
]].dropna()

# Gruppieren nach Jahr & Mittelwert berechnen
avg_by_year = (
    yearly_consumption
    .groupby("Year")["Annual Petroleum Consumption For Fuel Type1"]
    .mean()
    .reset_index()
    .rename(columns={"Annual Petroleum Consumption For Fuel Type1": "Ø Erdölverbrauch (Gallonen/Jahr)"})
)

# Sortieren nach Jahr (optional, falls nicht chronologisch)
avg_by_year = avg_by_year.sort_values("Year")

# Plot: Liniendiagramm
fig = px.line(
    avg_by_year,
    x="Year",
    y="Ø Erdölverbrauch (Gallonen/Jahr)",
    title="Entwicklung des durchschnittlichen Erdölverbrauchs nach Modelljahr",
    markers=True,
    labels={"Year": "Modelljahr"},
    template="plotly_white"
)

fig.update_traces(line_color="green")
fig.show()

### 5. Welche Fahrzeugklassen verbrauchen am meisten Erdöl pro Jahr?

In [21]:
# Spalten auswählen & fehlende Werte entfernen
vehicles_filtered = vehicles[["Vehicle Size Class", "Annual Petroleum Consumption For Fuel Type1"]].dropna()

# Gruppieren nach Fahrzeugklasse
verbrauch_nach_klasse = (
    vehicles_filtered
    .groupby("Vehicle Size Class")["Annual Petroleum Consumption For Fuel Type1"]
    .mean()
    .reset_index()
    .rename(columns={"Annual Petroleum Consumption For Fuel Type1": "Ø Verbrauch (Gallonen/Jahr)"})
)

# Nach Verbrauch sortieren
verbrauch_nach_klasse = verbrauch_nach_klasse.sort_values("Ø Verbrauch (Gallonen/Jahr)", ascending=False)

# Plot erstellen
fig = px.bar(
    verbrauch_nach_klasse,
    x="Ø Verbrauch (Gallonen/Jahr)",
    y="Vehicle Size Class",
    orientation="h",
    title="Ø jährlicher Erdölverbrauch nach Fahrzeugklasse",
    labels={"Vehicle Class": "Fahrzeugklasse"},
    color="Ø Verbrauch (Gallonen/Jahr)",
    color_continuous_scale="Reds",
    )

fig.update_layout(template="plotly_white")
fig.show()

### 6. Welche Marken dominieren bei den Modellen mit dem geringsten Erdölverbrauch?

In [22]:
'Make'
'Model'

'Model'

### 7. Wie viele Fahrzeuge haben Plug-in-Hybrid-Eigenschaften (PHEV)?

In [28]:
vehicles2 = vehicles["Hybrid"].unique()
vehicles2

array([False,  True])

In [30]:
vehicles2_number = vehicles["Hybrid"].value_counts()
vehicles2_number

Hybrid
False    47240
True       283
Name: count, dtype: int64

In [23]:
vehicles.rename(columns={'PHEV Blended':'Hybrid'}, inplace=True)

In [24]:
# Anzahl Hybrid?    Fahrzeuge        Anzahl
# False    47240    konventionell     47240
# True       283    Hybrid              283

In [ ]:
konventionell_hybrid = vehicles.Hybrid.value_counts()

# px.bar(vehicles.Hybrid,
#        x=konventionell_hybrid,
#        y=konventionell_hybrid,
#        title='Fahrzeuge mit Hybrid Eigenschaften',
#        color='Hybrid',
#        template='plotly_white')

# fig.update_layout(showlegend=False)
# fig.show()

ValueError: All arguments should have the same length. The length of column argument `df[color]` is 47523, whereas the length of previously-processed arguments ['x', 'y'] is 2

### 8. Frage Untersuche, ob Plug-in-Hybride (PHEVs) im Vergleich zu konventionellen Fahrzeugen (z. B. Benzin, Diesel) weniger Erdöl pro Jahr verbrauchen.
Ist der Erdölverbrauch bei Hybrid oder konventionellen Fahrzeugen pro Jahr geringer?
Ist der Erdölverbrauch pro Jahr bei Hybrid oder konventionellen Fahrzeugen geringer?
Welche Fahrzeuge haben einen geringeren Erdölverbrauch pro Jahr, Hybrid oder konventionelle Fahrzeuge?

In [ ]:
# Vergleich des Erdölverbrauchs pro Jahr für Hybrid und konventionelle Fahrzeuge
vehicles.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 47523 entries, 0 to 47522
Data columns (total 63 columns):
 #   Column                                       Non-Null Count  Dtype
---  ------                                       --------------  -----
 0   Make                                         47523 non-null  object
 1   Model                                        47523 non-null  object
 2   Annual Petroleum Consumption For Fuel Type1  47523 non-null  float64
 3   Annual Petroleum Consumption For Fuel Type2  47523 non-null  float64
 4   Time to charge at 120V                       47523 non-null  float64
 5   Time to charge at 240V                       47523 non-null  float64
 6   City Mpg For Fuel Type1                      47523 non-null  int64
 7   Unrounded City Mpg For Fuel Type1 (2)        47523 non-null  float64
 8   City Mpg For Fuel Type2                      47523 non-null  int64
 9   Unrounded City Mpg For Fuel Type2            47523 non-null  float64
 10  City gasoline consumption                    47523 non-null  float64
 11  City electricity consumption                 47523 non-null  float64
 12  EPA city utility factor                      47523 non-null  float64
 13  Co2 Fuel Type1                               47523 non-null  int64
 14  Co2 Fuel Type2                               47523 non-null  int64
 15  Co2  Tailpipe For Fuel Type2                 47523 non-null  float64
 16  Co2  Tailpipe For Fuel Type1                 47523 non-null  float64
 17  Combined Mpg For Fuel Type1                  47523 non-null  int64
 18  Unrounded Combined Mpg For Fuel Type1        47523 non-null  float64
 19  Combined Mpg For Fuel Type2                  47523 non-null  int64
 20  Unrounded Combined Mpg For Fuel Type2        47523 non-null  float64
 21  Combined electricity consumption             47523 non-null  float64
 22  Combined gasoline consumption                47523 non-null  float64
 23  EPA combined utility factor                  47523 non-null  float64
 24  EPA model type index                         47523 non-null  int64
 25  Annual Fuel Cost For Fuel Type1              47523 non-null  int64
 26  Annual Fuel Cost For Fuel Type2              47523 non-null  int64
 27  Fuel Type                                    47523 non-null  object
 28  Fuel Type1                                   47523 non-null  object
 29  Highway Mpg For Fuel Type1                   47523 non-null  int64
 30  Unrounded Highway Mpg For Fuel Type1         47523 non-null  float64
 31  Highway Mpg For Fuel Type2                   47523 non-null  int64
 32  Unrounded Highway Mpg For Fuel Type2         47523 non-null  float64
 33  Highway gasoline consumption                 47523 non-null  float64
 34  Highway electricity consumption              47523 non-null  float64
 35  EPA highway utility factor                   47523 non-null  float64
 36  Hatchback luggage volume                     47523 non-null  int64
 37  Hatchback passenger volume                   47523 non-null  int64
 38  ID                                           47523 non-null  int64
 39  2 door luggage volume                        47523 non-null  int64
 40  4 door luggage volume                        47523 non-null  int64
 41  Hybrid                                       47523 non-null  bool
 42  2-door passenger volume                      47523 non-null  int64
 43  4-door passenger volume                      47523 non-null  int64
 44  Range For Fuel Type1                         47523 non-null  int64
 45  Range  City For Fuel Type1                   47523 non-null  float64
 46  Range  City For Fuel Type2                   47523 non-null  float64
 47  Range  Highway For Fuel Type1                47523 non-null  float64
 48  Range  Highway For Fuel Type2                47523 non-null  float64
 49  Unadjusted City Mpg For Fuel Type1           47523 non-null  float64
 50  Unadjusted City Mpg For Fuel Type2           47523 non-null  float64
 51  Unadjusted Highway Mpg For Fuel Type1        47523 non-null  float64
 52  Unadjusted Highway Mpg For Fuel Type2        47523 non-null  float64
 53  Vehicle Size Class                           47523 non-null  object
 54  Year                                         47523 non-null  int64
 55  You Save/Spend                               47523 non-null  int64
 56  charge240b                                   47523 non-null  float64
 57  Created On                                   47523 non-null  object
 58  Modified On                                  47523 non-null  object
 59  PHEV City                                    47523 non-null  int64
 60  PHEV Highway                                 47523 non-null  int64
 61  PHEV Combined                                47523 non-null  int64
 62  baseModel                                    47523 non-null  object
dtypes: bool(1), float64(30), int64(24), object(8)
memory usage: 22.5+ MB

### 9.

### 10.