In [1]:
import pandas as pd
import numpy as np

In [2]:
data = { 'Year': [2022, 2022, 2022, 2023, 2023, 2023, 2024, 2024, 2024, 2022, 2023, 2024, 2022, 2023, 2024, 2022, 2023, 2024, 2022, 2023, 2024], 'Country': ['USA', 'USA', 'USA', 'USA', 'USA', 'USA', 'USA', 'USA', 'USA', 'UK', 'UK', 'UK', 'Germany', 'Germany', 'Germany', 'UK', 'UK', 'UK', 'Germany', 'Germany', 'Germany'], 'State': ['MA', 'NY', 'IL', 'MA', 'NY', 'IL', 'MA', 'NY', 'IL', 'England', 'England', 'England', 'Berlin', 'Berlin', 'Berlin', 'Scotland', 'Scotland', 'Scotland', 'Hamburg', 'Hamburg', 'Hamburg'], 'City': ['Boston', 'New York', 'Chicago', 'Boston', 'New York', 'Chicago', 'Boston', 'New York', 'Chicago', 'London', 'London', 'London', 'Berlin', 'Berlin', 'Berlin', 'Edinburgh', 'Edinburgh', 'Edinburgh', 'Hamburg', 'Hamburg', 'Hamburg'], 'Runners': [30000, 50000, 45000, 31000, 51000, 46000, 32000, 52000, 47000, 42000, 43000, 44000, 39000, 40000, 41000, 15000, 16000, 17000, 18000, 19000, 20000] }

In [4]:
df = pd.DataFrame(data)

In [5]:
df.head(20)

    Year  Country     State       City  Runners
0   2022      USA        MA     Boston    30000
1   2022      USA        NY   New York    50000
2   2022      USA        IL    Chicago    45000
3   2023      USA        MA     Boston    31000
4   2023      USA        NY   New York    51000
5   2023      USA        IL    Chicago    46000
6   2024      USA        MA     Boston    32000
7   2024      USA        NY   New York    52000
8   2024      USA        IL    Chicago    47000
9   2022       UK   England     London    42000
10  2023       UK   England     London    43000
11  2024       UK   England     London    44000
12  2022  Germany    Berlin     Berlin    39000
13  2023  Germany    Berlin     Berlin    40000
14  2024  Germany    Berlin     Berlin    41000
15  2022       UK  Scotland  Edinburgh    15000
16  2023       UK  Scotland  Edinburgh    16000
17  2024       UK  Scotland  Edinburgh    17000
18  2022  Germany   Hamburg    Hamburg    18000
19  2023  Germany   Hamburg    Hamburg    19000

In [7]:
pivot_df = df.pivot(index='Year', columns='City', values='Runners')

In [8]:
pivot_df.head(10)

City  Berlin  Boston  Chicago  Edinburgh  Hamburg  London  New York
Year
2022   39000   30000    45000      15000    18000   42000     50000
2023   40000   31000    46000      16000    19000   43000     51000
2024   41000   32000    47000      17000    20000   44000     52000

In [9]:
pivot_with_totals = df.pivot_table(index='Year', columns='City', values='Runners', aggfunc='sum', margins=True, margins_name='Total')

In [10]:
pivot_with_totals.head(10)

City   Berlin  Boston  Chicago  Edinburgh  Hamburg  London  New York   Total
Year
2022    39000   30000    45000      15000    18000   42000     50000  239000
2023    40000   31000    46000      16000    19000   43000     51000  246000
2024    41000   32000    47000      17000    20000   44000     52000  253000
Total  120000   93000   138000      48000    57000  129000    153000  738000

In [11]:
multi_agg_pivot = df.pivot_table(index='Year', columns='Country', values='Runners', aggfunc=['sum', 'mean', 'max', 'min'])

In [12]:
multi_agg_pivot.head(10)

            sum                    mean                            max         \
Country Germany     UK     USA  Germany       UK           USA Germany     UK
Year
2022      57000  57000  125000  28500.0  28500.0  41666.666667   39000  42000
2023      59000  59000  128000  29500.0  29500.0  42666.666667   40000  43000
2024      61000  61000  131000  30500.0  30500.0  43666.666667   41000  44000

                   min
Country    USA Germany     UK    USA
Year
2022     50000   18000  15000  30000
2023     51000   19000  16000  31000
2024     52000   20000  17000  32000

In [13]:
data2 = { 'Year': [2022, 2022, 2022, 2022, 2022, 2022, 2022, 2022, 2023, 2023, 2023, 2023, 2023, 2023, 2023, 2023, 2024, 2024, 2024, 2024, 2024, 2024, 2024, 2024] * 4, 'Race Category': ['5K', '10K', 'Half Marathon', 'Marathon'] * 24, 'Age Group': ['18-29', '18-29', '18-29', '18-29', '30-39', '30-39', '30-39', '30-39', '40-49', '40-49', '40-49', '40-49', '50+', '50+', '50+', '50+'] * 6, 'Gender': ['Male'] * 48 + ['Female'] * 48, 'Participants': [1200, 1300, 1100, 900, 1400, 1500, 1300, 1100, 1000, 1100, 950, 800, 800, 900, 850, 700, 1300, 1400, 1200, 1000, 1500, 1600, 1400, 1200, 1100, 1200, 1050, 900, 900, 1000, 950, 800, 1400, 1500, 1300, 1100, 1600, 1700, 1500, 1300, 1200, 1300, 1150, 1000, 1000, 1100, 1050, 900] * 2 }

In [14]:
df_race = pd.DataFrame(data2)

In [15]:
df_race.head(10)

   Year  Race Category Age Group Gender  Participants
0  2022             5K     18-29   Male          1200
1  2022            10K     18-29   Male          1300
2  2022  Half Marathon     18-29   Male          1100
3  2022       Marathon     18-29   Male           900
4  2022             5K     30-39   Male          1400
5  2022            10K     30-39   Male          1500
6  2022  Half Marathon     30-39   Male          1300
7  2022       Marathon     30-39   Male          1100
8  2023             5K     40-49   Male          1000
9  2023            10K     40-49   Male          1100

In [38]:
multi_pivot_race = df_race.pivot_table(index=['Year', 'Gender'], columns=['Race Category', 'Age Group'], values='Participants', aggfunc='sum')

In [32]:
desired_order = ['5K', '10K', 'Half Marathon', 'Marathon']

In [33]:
multi_pivot_race = multi_pivot_race.copy()

In [35]:
multi_pivot_race = multi_pivot_race.sort_index( axis=1, level=0, key=lambda x: [desired_order.index(i) if i in desired_order else len(desired_order) for i in x.get_level_values(0)])

In [36]:
multi_pivot_race.head()

Race Category    5K                     10K                   Half Marathon  \
Age Group     18-29 30-39 40-49   50+ 18-29 30-39 40-49   50+         18-29
Year Gender
2022 Female    1200  1400  1100   900  1300  1500  1200  1000          1100
     Male      1200  1400  1100   900  1300  1500  1200  1000          1100
2023 Female    1400  1600  1000   800  1500  1700  1100   900          1300
     Male      1400  1600  1000   800  1500  1700  1100   900          1300
2024 Female    1300  1500  1200  1000  1400  1600  1300  1100          1200

Race Category                   Marathon
Age Group     30-39 40-49   50+    18-29 30-39 40-49  50+
Year Gender
2022 Female    1300  1050   950      900  1100   900  800
     Male      1300  1050   950      900  1100   900  800
2023 Female    1500   950   850     1100  1300   800  700
     Male      1500   950   850     1100  1300   800  700
2024 Female    1400  1150  1050     1000  1200  1000  900

In [21]:
data3 = { 'Runner': ['Ryan', 'Bob', 'Ryan', 'Bob', 'Charlie', 'Charlie', 'Ryan'], 'Race': ['Boston', 'Boston', 'NYC', 'NYC', 'Chicago', 'Boston', 'Chicago'], 'Time': [3.5, np.nan, 3.8, 4.2, 4.0, np.nan, 3.7] }

In [22]:
df3 = pd.DataFrame(data3)

In [23]:
df3.head()

    Runner     Race  Time
0     Ryan   Boston   3.5
1      Bob   Boston   NaN
2     Ryan      NYC   3.8
3      Bob      NYC   4.2
4  Charlie  Chicago   4.0

In [24]:
pivot_table_null_values = df3.pivot_table(index='Runner', columns='Race', values='Time', aggfunc='mean', fill_value="Did Not Run")

In [25]:
pivot_table_null_values.head()

Race          Boston      Chicago          NYC
Runner
Bob      Did Not Run  Did Not Run          4.2
Charlie  Did Not Run          4.0  Did Not Run
Ryan             3.5          3.7          3.8

In [26]:
data_error = {'Runner': ['Ryan', 'Ryan', 'Bob', 'Bob'], 'Race': ['Boston', 'Boston', 'NYC', 'NYC'], 'Time': [3.5, 3.6, 4.2, 4.3]} # Multiple times for same race

In [27]:
df_error = pd.DataFrame(data_error)

In [28]:
df_error.head()

  Runner    Race  Time
0   Ryan  Boston   3.5
1   Ryan  Boston   3.6
2    Bob     NYC   4.2
3    Bob     NYC   4.3

In [ ]:
# pivot_df_multi = df_error.pivot(index='Runner', columns='Race', values='Time')
# ValueError: Index contains duplicate entries, cannot reshape
# solution below :)

In [37]:
pivot_table_df = df_error.pivot_table(index='Runner', columns='Race', values='Time', aggfunc='mean')

In [31]:
pivot_table_df.head(10)

Race    Boston   NYC
Runner
Bob        NaN  4.25
Ryan      3.55   NaN